import type { Metadata } from 'next'

import { Geist, Geist_Mono } from 'next/font/google'
import './main-layout.scss'
import Header from '@/app/components/Header/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div className="container">{children}</div>
      </body>
    </html>
  )
}
